name: ss
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - mne
  - tqdm
  - einops
  - wfdb
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit
  - matplotlib
  - ipykernel
  - lightning
  - tensorboard
